swagger: '2.0'
info:
  title: Hello API
  description: Hello API
  version: 1.0.0
schemes:
  - http

basePath: /

produces:
  - application/json

paths:
  /product/getProduct:
    get:
      tags:
        - product
      operationId: getProduct
      parameters:
        - name: productId
          description: the request to get product
          in: query
          required: true
          type: integer

      responses:
        '200':
          description: response
          schema:
            $ref: '#/definitions/ProductResponse'

  /product/create:
    post:
      tags:
        - product
      operationId: createProduct
      parameters:
        - name: createProductRequest
          in: body
          schema:
            $ref: '#/definitions/ProductRequest'
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ProductResponse'
  /health:
    get:
      tags:
        - health
      operationId: getHealth
      responses:
        '200':
          name: result
          description: OK
          type: string


definitions:
  Partner:
    type: string
    enum: &PARTNER [CTRIP, ELONG]

  ProductRequest:
    description: The request to get product
    properties:
      productId:
        type: integer
      productName:
        type: string
      partner:
        $ref: '#/definitions/Partner'
      price:
        type: number
        format: double
      sellable:
        type: boolean
      cancellationPolicies:
        type: array
        items:
          type: string

  ProductResponse:
    description: the response for the product
    type: object
    properties:
      success:
        type: boolean
      errorCode:
        type: string
      errorMessage:
        type: string
      data:
        $ref: '#/definitions/Product'

  Product:
    type: object
    properties:
      productId:
        type: integer
      productName:
        type: string
      partner:
        $ref: '#/definitions/Partner'
      price:
        type: number
        format: double
      sellable:
        type: boolean
      cancellationPolicies:
        type: array
        items:
          type: string
